openapi: 3.0.1
info:
  title: Local Files Plugin
  description: Access and search local files
  version: '1.0.0'
servers:
  - url: http://localhost:9900
paths:
  /search:
    get:
      summary: Search local files
      operationId: searchFiles
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Search results
